/**
 * Created by joe on 1/11/17.
 */
public class SampleVirusSequences {


        String VarisellaZoster = "GGCCCTCTCCCCCCTAAAAAACCCACTCCGCCTTTCCCATCGATATTTTTTCGACCCCCCCCCGCCTTTAAAACCCCCCTTTTGCGTCCCCCCTCTTTCTCTCGATGCGCCGTCCTACTCCCCCGACCTGACCCCGCTACCTCACGTCGTCCCCCTCTGGATCGTTGCCCCCTCCCCTCCTCCACTCCCGGCCGTGCAGACCCCCCCCTTACCCGAGTCTGTTTCTCCCGCCTCTTTTTCCTCAGTGGATGCACCCCCCTCTTCTTCCTACTCGCTTTTGGATCCCAGCTTCAGCTGCTTTTCTAGATTCCTCTTGTACCGCTTTTTTTTCTTTTTGTTTCTCCCCTT";//~CT6CT~TC6T~TC~CCkTT~TTGCCG~TTTCCCG~kCCTC~CAkCTCAkCTkCkT~kkCTACT6~CC~kGG~AkG6TjT~Tk~TCTC~CTT";

        public SampleVirusSequences() {
        }

        public String getVarisellaZoster() {
            return VarisellaZoster;
        }

        public void setVarisellaZoster(String varisellaZoster) {
                VarisellaZoster = varisellaZoster;
        }
}
